#!/bin/bash

CHILLI=/etc/chilli

[ "$1" == "-h" -o "$1" == "--help" ] && {
    echo "chilli_cfg dev cfg_name=cfg_value [...]"
    echo "chilli_cfg printcfg"
    exit 0
}

[ "$1" == "printcfg" ] && {
    cat $CHILLI/defaults | grep HS_
    exit 0
}

[ -f "$CHILLI/config" ] || cp $CHILLI/defaults $CHILLI/config

for config in $*;
do
    echo "chilli config: $config"

    argv=($(echo $config | sed 's/=/ /g'))

    if [ ${#argv[@]} == 1 ]; then
        sudo sed -i "s/.*${argv[0]}=.*/#$config=/" $CHILLI/config
    elif [ ${#argv[@]} == 2 ]; then
        sudo sed -i "s/.*${argv[0]}=.*/$config/" $CHILLI/config
    else
        echo "Wrong parameter: $config, format: cfg_name=cfg_value."
    fi
done
